spring.application.name=capstone

server.port=${PORT:3000}

spring.datasource.url=jdbc:postgresql://localhost:5436/flyrank_capstone
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

app.jwt.secret=${JWT_SECRET:dev_only_change_this_in_real_env}
app.jwt.expiration-ms=86400000

app.geo.provider-a-url=${GEO_PROVIDER_A_URL:http://ip-api.com/json}
app.geo.provider-b-url=${GEO_PROVIDER_B_URL:https://ipapi.co}
